query PageQuery {
  ...LayoutQueryFragment
}

query ContentQuery($relativePath: String!) {
  pages(relativePath: $relativePath) {
    ...PagesParts
  }
}

query EventQuery($relativePath: String!) {
  events(relativePath: $relativePath) {
    ...EventsParts
  }
}