fragment GlobalParts on Global {
  header {
    __typename
    nav {
      __typename
      href
      label
    }
  }
}

fragment PagesParts on Pages {
  seo {
    __typename
    title
    description
  }
  blocks {
    __typename
    ... on PagesBlocksHero {
      image {
        __typename
        src
        alt
      }
      headline
      tagline
      as_banner
    }
    ... on PagesBlocksContent {
      name
      bgColor
      size_large
      body
    }
    ... on PagesBlocksIntroduction {
      title
      text
      image {
        __typename
        src
        alt
      }
    }
    ... on PagesBlocksFeature {
      subhead
      title
      link {
        __typename
        label
        url
      }
    }
    ... on PagesBlocksTextAndImage {
      showIllustrations
      bgColor
      title
      body
      image {
        __typename
        src
        alt
      }
      image_position
      link {
        __typename
        label
        url
      }
    }
    ... on PagesBlocksTestimonials {
      title
      testimonial {
        __typename
        type
        author
        text
      }
    }
    ... on PagesBlocksEvents {
      title
      location {
        ... on Location {
          name
          description
          image
        }
        ... on Document {
          id
        }
      }
      stage
      show_all_link
      limit
    }
  }
}

fragment EventsParts on Events {
  title
  start_date
  end_date
  location {
    ... on Location {
      name
      description
      image
    }
    ... on Document {
      id
    }
  }
  type
  external_link
  description
}

fragment LocationParts on Location {
  name
  description
  image
}
