fragment GlobalParts on Global {
  header {
    __typename
    nav {
      __typename
      href
      label
    }
  }
}

fragment PagesParts on Pages {
  blocks {
    __typename
    ... on PagesBlocksHero {
      headline
      tagline
    }
    ... on PagesBlocksContent {
      body
    }
    ... on PagesBlocksIntroduction {
      title
      text
      image {
        __typename
        src
        alt
      }
    }
    ... on PagesBlocksFeature {
      subhead
      title
      link {
        __typename
        label
        url
      }
    }
    ... on PagesBlocksTextAndImage {
      showIllustrations
      bgColor
      title
      body
      image {
        __typename
        src
        alt
      }
      image_position
      link {
        __typename
        label
        url
      }
    }
    ... on PagesBlocksEvents {
      subhead
      title
    }
  }
}

fragment EventsParts on Events {
  title
  start_date
  end_date
  location
  type
  description
}
